
package com.example.attendance.ai;

import com.google.genai.Client;
import com.google.genai.types.GenerateContentResponse;
import org.springframework.stereotype.Service;

@Service
public class GeminiAiService {

    private final Client client;

    public GeminiAiService() {

        String apiKey =
                System.getenv("GEMINI_API_KEY");

        if (apiKey == null || apiKey.isBlank()) {

            throw new IllegalStateException(
                    "GEMINI_API_KEY environment variable is not configured."
            );
        }

        this.client =
                Client.builder()
                        .apiKey(apiKey)
                        .build();
    }

    public String generateResponse(String prompt) {

        if (prompt == null || prompt.isBlank()) {

            return "Please enter a valid question.";
        }

        String cleanPrompt =
                prompt.trim();

        /*
         * Primary model
         */
        try {

            return generateWithModel(
                    "gemini-3.8-flash",
                    cleanPrompt
            );

        } catch (Exception primaryException) {

            /*
             * Fallback model
             */
            try {

                return generateWithModel(
                        "gemini-3.7-flash",
                        cleanPrompt
                );

            } catch (Exception fallbackException) {

                return "AI service error: "
                        + fallbackException.getMessage();
            }
        }
    }

    private String generateWithModel(
            String model,
            String prompt) {

        GenerateContentResponse response =
                client.models.generateContent(
                        model,
                        prompt,
                        null
                );

        String text =
                response.text();

        if (text == null || text.isBlank()) {

            throw new IllegalStateException(
                    "No response was generated by "
                            + model
            );
        }

        return text.trim();
    }
}

