spring.application.name=attendance

# ===============================
# SQL Server Database
# ===============================
spring.datasource.url=jdbc:sqlserver://localhost:62876;databaseName=growbytee_attendance;encrypt=true;trustServerCertificate=true
spring.datasource.username=attendance_user
spring.datasource.password=Attend@12345
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# ===============================
# JPA / Hibernate
# ===============================
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect

# ===============================
# Server
# ===============================
server.port=8080