spring.application.name=attendance

# ===============================
# Supabase PostgreSQL Database
# ===============================
spring.datasource.url=jdbc:postgresql://db.vpnsebakkhhjscnckzsg.supabase.co:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=Sandy@2813#supabase
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / Hibernate
# ===============================
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# ===============================
# Server
# ===============================
server.port=8080